package view;

import controller.EmptyValueException;
import controller.IOFile;
import controller.NegativeNumException;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import model.BookModel;
import model.QLSModel;

public class FormBook extends javax.swing.JPanel {

   DefaultTableModel tableModel;
   private boolean adding, editting;
   private String filePath;
   private List<BookModel> books;
    public FormBook() {
        initComponents();
        String[] cols = {"Mã sách", "Tên sách", "Tác giả", "Thể loại", "Số lượng"};
        tableModel = new DefaultTableModel(cols, 0);
        jTable1.setModel(tableModel);
        txtfieldBookCode.setEditable(false);
        buttonState(true);
        adding = false;
        editting = false;
        filePath = "src/controller/book.txt";
        initData();
    }
    
    private void initData(){ 
        File file = new File(filePath);
        if(file.exists()){
           books = IOFile.doc(filePath);
        }
    }
    
    private void buttonState(boolean e){
        btnAddBook.setEnabled(e);
        btnEditBook.setEnabled(e);
        btnUpdate.setEnabled(!e);
        btnSkip.setEnabled(!e);
    }
    
    private void showData(List<BookModel> list){
        tableModel.setRowCount(0);
        for(BookModel i : list){
            tableModel.addRow(i.toObjects());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfieldBookCode = new javax.swing.JTextField();
        txtfieldBookName = new javax.swing.JTextField();
        txtfieldAuthor = new javax.swing.JTextField();
        txtfieldAmount = new javax.swing.JTextField();
        btnAddBook = new javax.swing.JButton();
        btnEditBook = new javax.swing.JButton();
        btxDeleteBook = new javax.swing.JButton();
        btnShowBook = new javax.swing.JButton();
        btnSaveToFile = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSkip = new javax.swing.JButton();
        comboBoxCategory = new javax.swing.JComboBox<>();
        txtFieldSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Mã sách");

        jLabel2.setText("Tên sách");

        jLabel3.setText("Tác giả");

        jLabel4.setText("Chuyên ngành");

        jLabel5.setText("Số lượng");

        txtfieldBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldBookNameActionPerformed(evt);
            }
        });

        txtfieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldAmountActionPerformed(evt);
            }
        });

        btnAddBook.setText("Thêm mới");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnEditBook.setText("Sửa");
        btnEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookActionPerformed(evt);
            }
        });

        btxDeleteBook.setText("Xóa");
        btxDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxDeleteBookActionPerformed(evt);
            }
        });

        btnShowBook.setText("Hiển thị");
        btnShowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowBookActionPerformed(evt);
            }
        });

        btnSaveToFile.setText("Lưu vào file");
        btnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveToFileActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSkip.setText("Bỏ qua");
        btnSkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipActionPerformed(evt);
            }
        });

        comboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa học tự nhiên", "Văn học", "Nghệ thuật", "Điện tử viễn thông", "Công nghệ thông tin" }));
        comboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCategoryActionPerformed(evt);
            }
        });

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(txtFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfieldBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtfieldBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtfieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtfieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSkip, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSaveToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                        .addComponent(btnShowBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                    .addComponent(btxDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfieldBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfieldBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaveToFile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btxDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSkip, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFieldSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
       buttonState(false);
       adding = true;
       jTable1.clearSelection();
       File file = new File(filePath);
       if(books!=null && books.size() > 0){
           BookModel.setSma(books.get(books.size()-1).getMa()+1);
       } else{
           books = new ArrayList<>();
       }
       txtfieldBookCode.setText(BookModel.getSma()+"");
       txtfieldBookName.requestFocus();
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void comboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCategoryActionPerformed

    private void txtfieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldAmountActionPerformed

    private void btnSkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipActionPerformed
          if(adding){
              adding = false;
          }
          buttonState(true);
         
    }//GEN-LAST:event_btnSkipActionPerformed

    private void txtfieldBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldBookNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(adding){
           try{
               String name = txtfieldBookName.getText();
               String author = txtfieldAuthor.getText();
               if(name.isEmpty() || author.isEmpty()){
                   throw new EmptyValueException();
               }
               int amount = Integer.parseInt(txtfieldAmount.getText());
               if(amount <= 0){
                   throw new NegativeNumException();
               }
               int id = Integer.parseInt(txtfieldBookCode.getText());
               BookModel book = new BookModel(
                    id,
                    name,
                    author,
                    comboBoxCategory.getSelectedItem().toString(),
                    amount
               );
               tableModel.addRow(book.toObjects());
               books.add(book);
               buttonState(true);
               adding = false;
            
           } catch (EmptyValueException e){
               JOptionPane.showMessageDialog(this, "Không để trống thông tin");
               txtfieldBookName.requestFocus();
           } catch (NegativeNumException e){
               JOptionPane.showMessageDialog(this, "Số lượng phải > 0");
               txtfieldAmount.requestFocus();
           } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Chỉ bao gồm số và > 0");
                txtfieldAmount.requestFocus();
           }
        }
        if(editting){
            try{
                int row = jTable1.getSelectedRow();
                String name, author;
                name = txtfieldBookName.getText();
                author = txtfieldAuthor.getText();
                int id = Integer.parseInt(txtfieldBookCode.getText());
                String cn = comboBoxCategory.getSelectedItem().toString();
                int s1 = Integer.parseInt(txtfieldAmount.getText());
                if(s1 <= 0) throw new NegativeNumException();
                if(name.isEmpty() || author.isEmpty() || cn.isEmpty()) throw new EmptyValueException();
                //int ma, String ten, String tacGia, String chuyenNganh, int soLuong
                BookModel book = new BookModel(
                        id, 
                        name, 
                        author,
                        cn, 
                        s1
                );
                tableModel.setValueAt(id, row, 0);
                tableModel.setValueAt(name, row, 1);
                tableModel.setValueAt(author, row, 2);
                tableModel.setValueAt(cn, row, 3);
                tableModel.setValueAt(s1, row, 4);
                books.set(row, book);
                editting = false;
                buttonState(true);
            } catch (NegativeNumException ex) {
                JOptionPane.showMessageDialog(this, "Số lượng lớn hơn 0");
                txtfieldAmount.requestFocus();
            } catch (EmptyValueException ex) {
                JOptionPane.showMessageDialog(this, "Không để trống thông tin");
                txtfieldBookName.requestFocus();
            } catch (NumberFormatException e ){
                JOptionPane.showMessageDialog(this, "Số lượng là số và lớn hơn 0");
            }
           
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btxDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxDeleteBookActionPerformed
        int currentRow = jTable1.getSelectedRow();
        if(currentRow<0 || currentRow > jTable1.getRowCount()-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách");
        } else{
            tableModel.removeRow(currentRow);
            books.remove(currentRow);
        }
    }//GEN-LAST:event_btxDeleteBookActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int currentRow = jTable1.getSelectedRow();
        if(currentRow<0 || currentRow > jTable1.getRowCount()-1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách");
        } else{
            txtfieldBookCode.setText(tableModel.getValueAt(currentRow, 0).toString());
            txtfieldBookName.setText(tableModel.getValueAt(currentRow, 1).toString());
            txtfieldAuthor.setText(tableModel.getValueAt(currentRow, 2).toString());
            txtfieldAmount.setText(tableModel.getValueAt(currentRow, 4).toString());
            String category = tableModel.getValueAt(currentRow, 3).toString();
            for(int i=0;i<comboBoxCategory.getItemCount(); i++){
                if(comboBoxCategory.getItemAt(i).toString().equalsIgnoreCase(category)){
                    comboBoxCategory.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveToFileActionPerformed
        IOFile.viet(filePath, books);
        JOptionPane.showMessageDialog(this, "đã lưu dữ liệu: " + filePath);
    }//GEN-LAST:event_btnSaveToFileActionPerformed

    private void btnShowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowBookActionPerformed
        try{
            initData();
            tableModel.setRowCount(0);
            for(BookModel bm: books){
                tableModel.addRow(bm.toObjects());
            }
        } catch (Exception e){
           JOptionPane.showMessageDialog(this, "Chưa có dữ liệu vui lòng nhập thêm");
        }
    }//GEN-LAST:event_btnShowBookActionPerformed

    private void btnEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookActionPerformed
        int row = jTable1.getSelectedRow();
        if( row < 0 || row > jTable1.getRowCount()-1){
            JOptionPane.showMessageDialog(this, "Chọn sách để sửa");
        } else{
            editting = true;
            buttonState(false);
            txtfieldBookName.requestFocus();

        }
    }//GEN-LAST:event_btnEditBookActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keySearch = txtFieldSearch.getText().trim().toLowerCase();
        List<BookModel> listResult = new ArrayList<>();
        for(BookModel i : books){
            if((i.getTen().toLowerCase().contains(keySearch))
                    || (i.getTacGia().toLowerCase().contains(keySearch))){
                listResult.add(i);
            }
        }
        showData(listResult);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnEditBook;
    private javax.swing.JButton btnSaveToFile;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowBook;
    private javax.swing.JButton btnSkip;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btxDeleteBook;
    private javax.swing.JComboBox<String> comboBoxCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtFieldSearch;
    private javax.swing.JTextField txtfieldAmount;
    private javax.swing.JTextField txtfieldAuthor;
    private javax.swing.JTextField txtfieldBookCode;
    private javax.swing.JTextField txtfieldBookName;
    // End of variables declaration//GEN-END:variables
}
